// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shh.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Claims struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{0}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Claims) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PublicKey struct {
	Pem                  string   `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{1}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPem() string {
	if m != nil {
		return m.Pem
	}
	return ""
}

type MessageToUnfold struct {
	Claims               *Claims  `protobuf:"bytes,3,opt,name=claims,proto3" json:"claims,omitempty"`
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	EncodedMessage       string   `protobuf:"bytes,2,opt,name=encodedMessage,proto3" json:"encodedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageToUnfold) Reset()         { *m = MessageToUnfold{} }
func (m *MessageToUnfold) String() string { return proto.CompactTextString(m) }
func (*MessageToUnfold) ProtoMessage()    {}
func (*MessageToUnfold) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{2}
}

func (m *MessageToUnfold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageToUnfold.Unmarshal(m, b)
}
func (m *MessageToUnfold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageToUnfold.Marshal(b, m, deterministic)
}
func (m *MessageToUnfold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageToUnfold.Merge(m, src)
}
func (m *MessageToUnfold) XXX_Size() int {
	return xxx_messageInfo_MessageToUnfold.Size(m)
}
func (m *MessageToUnfold) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageToUnfold.DiscardUnknown(m)
}

var xxx_messageInfo_MessageToUnfold proto.InternalMessageInfo

func (m *MessageToUnfold) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *MessageToUnfold) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *MessageToUnfold) GetEncodedMessage() string {
	if m != nil {
		return m.EncodedMessage
	}
	return ""
}

type MessageToFold struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageToFold) Reset()         { *m = MessageToFold{} }
func (m *MessageToFold) String() string { return proto.CompactTextString(m) }
func (*MessageToFold) ProtoMessage()    {}
func (*MessageToFold) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{3}
}

func (m *MessageToFold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageToFold.Unmarshal(m, b)
}
func (m *MessageToFold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageToFold.Marshal(b, m, deterministic)
}
func (m *MessageToFold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageToFold.Merge(m, src)
}
func (m *MessageToFold) XXX_Size() int {
	return xxx_messageInfo_MessageToFold.Size(m)
}
func (m *MessageToFold) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageToFold.DiscardUnknown(m)
}

var xxx_messageInfo_MessageToFold proto.InternalMessageInfo

func (m *MessageToFold) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *MessageToFold) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Message struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type EncodedMessage struct {
	EncodedMessage       []byte   `protobuf:"bytes,1,opt,name=encodedMessage,proto3" json:"encodedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodedMessage) Reset()         { *m = EncodedMessage{} }
func (m *EncodedMessage) String() string { return proto.CompactTextString(m) }
func (*EncodedMessage) ProtoMessage()    {}
func (*EncodedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1369f85988ad79b5, []int{5}
}

func (m *EncodedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedMessage.Unmarshal(m, b)
}
func (m *EncodedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedMessage.Marshal(b, m, deterministic)
}
func (m *EncodedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedMessage.Merge(m, src)
}
func (m *EncodedMessage) XXX_Size() int {
	return xxx_messageInfo_EncodedMessage.Size(m)
}
func (m *EncodedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedMessage proto.InternalMessageInfo

func (m *EncodedMessage) GetEncodedMessage() []byte {
	if m != nil {
		return m.EncodedMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*Claims)(nil), "proto.Claims")
	proto.RegisterType((*PublicKey)(nil), "proto.PublicKey")
	proto.RegisterType((*MessageToUnfold)(nil), "proto.MessageToUnfold")
	proto.RegisterType((*MessageToFold)(nil), "proto.MessageToFold")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*EncodedMessage)(nil), "proto.EncodedMessage")
}

func init() { proto.RegisterFile("proto/shh.proto", fileDescriptor_1369f85988ad79b5) }

var fileDescriptor_1369f85988ad79b5 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0x6e, 0x2d, 0x76, 0xf6, 0xcc, 0x76, 0x33, 0xa8, 0x94, 0xa2, 0x30, 0x22, 0xca, 0xae, 0x26,
	0x4c, 0x10, 0x05, 0x2f, 0x04, 0xd1, 0x0d, 0x44, 0x90, 0xa9, 0x0f, 0xd0, 0xb5, 0x47, 0x37, 0x68,
	0x9b, 0xd2, 0x6c, 0x88, 0x37, 0x3e, 0x96, 0xcf, 0x27, 0x6d, 0x92, 0xd6, 0x14, 0xd9, 0x55, 0x73,
	0xbe, 0xf3, 0xfd, 0x25, 0x85, 0x5e, 0x5e, 0xb0, 0x15, 0x3b, 0xe7, 0x8b, 0xc5, 0xa8, 0x3a, 0x91,
	0xed, 0xea, 0x43, 0x6f, 0xc1, 0xbe, 0x4b, 0xc2, 0x65, 0xca, 0x49, 0x00, 0x3b, 0x6b, 0x8e, 0x45,
	0x16, 0xa6, 0xe8, 0x9b, 0x03, 0x73, 0xe8, 0xcc, 0xea, 0xb9, 0xdc, 0xe5, 0x21, 0xe7, 0x9f, 0xac,
	0x88, 0xfd, 0x2d, 0xb1, 0x53, 0x33, 0x3d, 0x06, 0xe7, 0x79, 0x3d, 0x4f, 0x96, 0xd1, 0x23, 0x7e,
	0x91, 0x3e, 0x58, 0x39, 0xa6, 0x52, 0x5f, 0x1e, 0xe9, 0x37, 0xf4, 0x9e, 0x90, 0xf3, 0xf0, 0x03,
	0x5f, 0xd9, 0x5b, 0xf6, 0xce, 0x92, 0x98, 0x9c, 0x82, 0x1d, 0x55, 0x99, 0xbe, 0x35, 0x30, 0x87,
	0xdd, 0xb1, 0x2b, 0x2a, 0x8d, 0x44, 0x91, 0x99, 0x5c, 0x92, 0x23, 0x70, 0x72, 0x65, 0x2c, 0x1d,
	0x1b, 0x80, 0x9c, 0x81, 0x87, 0x59, 0xc4, 0x62, 0x8c, 0xa5, 0xbd, 0x2c, 0xd6, 0x42, 0xe9, 0x04,
	0xdc, 0x3a, 0xff, 0xa1, 0x4c, 0xdf, 0x6c, 0xeb, 0x43, 0x27, 0xd5, 0xfc, 0xd4, 0x48, 0x4f, 0xa0,
	0x23, 0x8d, 0xfe, 0x92, 0x4a, 0x83, 0xdd, 0x86, 0x74, 0x05, 0xde, 0xbd, 0x96, 0xff, 0x4f, 0x4f,
	0x21, 0x69, 0xa1, 0xe3, 0x1f, 0x13, 0xac, 0x97, 0xe9, 0x94, 0x5c, 0xc2, 0xde, 0x04, 0x33, 0x2c,
	0xc2, 0x15, 0x36, 0xcf, 0xaa, 0xbf, 0x50, 0xd0, 0x97, 0x63, 0x4d, 0xa0, 0x06, 0xb9, 0x81, 0x6e,
	0x79, 0x3d, 0x15, 0xbb, 0x2f, 0x29, 0xda, 0xdd, 0x83, 0x03, 0x89, 0xea, 0x1d, 0xa9, 0x41, 0xae,
	0xc1, 0x15, 0x3f, 0x47, 0xe9, 0x0f, 0xdb, 0x7a, 0xb1, 0x0e, 0x3c, 0x1d, 0xa7, 0xc6, 0xdc, 0xae,
	0x80, 0x8b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xd1, 0x98, 0x52, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SHHClient is the client API for SHH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SHHClient interface {
	GeneratePublicKey(ctx context.Context, in *Claims, opts ...grpc.CallOption) (*PublicKey, error)
	FoldMessage(ctx context.Context, in *MessageToFold, opts ...grpc.CallOption) (*EncodedMessage, error)
	UnfoldMessage(ctx context.Context, in *MessageToUnfold, opts ...grpc.CallOption) (*Message, error)
}

type sHHClient struct {
	cc *grpc.ClientConn
}

func NewSHHClient(cc *grpc.ClientConn) SHHClient {
	return &sHHClient{cc}
}

func (c *sHHClient) GeneratePublicKey(ctx context.Context, in *Claims, opts ...grpc.CallOption) (*PublicKey, error) {
	out := new(PublicKey)
	err := c.cc.Invoke(ctx, "/proto.SHH/GeneratePublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHHClient) FoldMessage(ctx context.Context, in *MessageToFold, opts ...grpc.CallOption) (*EncodedMessage, error) {
	out := new(EncodedMessage)
	err := c.cc.Invoke(ctx, "/proto.SHH/FoldMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHHClient) UnfoldMessage(ctx context.Context, in *MessageToUnfold, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/proto.SHH/UnfoldMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SHHServer is the server API for SHH service.
type SHHServer interface {
	GeneratePublicKey(context.Context, *Claims) (*PublicKey, error)
	FoldMessage(context.Context, *MessageToFold) (*EncodedMessage, error)
	UnfoldMessage(context.Context, *MessageToUnfold) (*Message, error)
}

// UnimplementedSHHServer can be embedded to have forward compatible implementations.
type UnimplementedSHHServer struct {
}

func (*UnimplementedSHHServer) GeneratePublicKey(ctx context.Context, req *Claims) (*PublicKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePublicKey not implemented")
}
func (*UnimplementedSHHServer) FoldMessage(ctx context.Context, req *MessageToFold) (*EncodedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FoldMessage not implemented")
}
func (*UnimplementedSHHServer) UnfoldMessage(ctx context.Context, req *MessageToUnfold) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfoldMessage not implemented")
}

func RegisterSHHServer(s *grpc.Server, srv SHHServer) {
	s.RegisterService(&_SHH_serviceDesc, srv)
}

func _SHH_GeneratePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Claims)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHHServer).GeneratePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SHH/GeneratePublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHHServer).GeneratePublicKey(ctx, req.(*Claims))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHH_FoldMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageToFold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHHServer).FoldMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SHH/FoldMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHHServer).FoldMessage(ctx, req.(*MessageToFold))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHH_UnfoldMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageToUnfold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHHServer).UnfoldMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SHH/UnfoldMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHHServer).UnfoldMessage(ctx, req.(*MessageToUnfold))
	}
	return interceptor(ctx, in, info, handler)
}

var _SHH_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SHH",
	HandlerType: (*SHHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePublicKey",
			Handler:    _SHH_GeneratePublicKey_Handler,
		},
		{
			MethodName: "FoldMessage",
			Handler:    _SHH_FoldMessage_Handler,
		},
		{
			MethodName: "UnfoldMessage",
			Handler:    _SHH_UnfoldMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shh.proto",
}
